const fs = require('fs');
const path = require('path');

// 单字名字库
const singleCharDB = {
  '辰': { meaning: '星辰、时光，寓意如星辰般璀璨，把握美好时光', category: '时间', tone: 2, pinyin: 'chén' },
  '昕': { meaning: '黎明、日出，寓意充满希望，朝气蓬勃', category: '时间', tone: 1, pinyin: 'xīn' },
  '晓': { meaning: '清晨、明白，寓意聪慧明理，如晨光般清新', category: '时间', tone: 3, pinyin: 'xiǎo' },
  '曦': { meaning: '晨光、阳光，寓意温暖光明，前程似锦', category: '时间', tone: 1, pinyin: 'xī' },
  '旭': { meaning: '旭日东升，寓意朝气蓬勃，前程光明', category: '时间', tone: 4, pinyin: 'xù' },
  '晨': { meaning: '清晨、早晨，寓意朝气蓬勃，充满希望', category: '时间', tone: 2, pinyin: 'chén' },
  '晖': { meaning: '阳光、光辉，寓意光彩照人，前程辉煌', category: '时间', tone: 1, pinyin: 'huī' },
  '曜': { meaning: '日光、照耀，寓意光芒万丈，才华出众', category: '时间', tone: 4, pinyin: 'yào' },
  '沐': { meaning: '沐浴、润泽，寓意受恩泽滋养，心灵纯净', category: '水', tone: 4, pinyin: 'mù' },
  '汐': { meaning: '潮汐、晚潮，寓意有规律、有节奏，温婉动人', category: '水', tone: 1, pinyin: 'xī' },
  '溪': { meaning: '溪流、小河，寓意清澈纯净，源远流长', category: '水', tone: 1, pinyin: 'xī' },
  '清': { meaning: '清澈、纯净，寓意品性高洁，心思澄明', category: '水', tone: 1, pinyin: 'qīng' },
  '涵': { meaning: '包容、涵养，寓意有内涵，心胸宽广', category: '水', tone: 2, pinyin: 'hán' },
  '泽': { meaning: '恩泽、光泽，寓意仁慈博爱，光彩照人', category: '水', tone: 2, pinyin: 'zé' },
  '澜': { meaning: '波澜、波浪，寓意气势磅礴，心胸宽广', category: '水', tone: 2, pinyin: 'lán' },
  '润': { meaning: '滋润、润泽，寓意温润如玉，泽被万物', category: '水', tone: 4, pinyin: 'rùn' },
  '潇': { meaning: '潇洒、洒脱，寓意洒脱不羁，风流倜傥', category: '水', tone: 1, pinyin: 'xiāo' },
  '湘': { meaning: '湘江、湖南，寓意温婉秀丽，才华横溢', category: '水', tone: 1, pinyin: 'xiāng' },
  '淇': { meaning: '淇水、美好，寓意温柔贤淑，品质高洁', category: '水', tone: 2, pinyin: 'qí' },
  '洛': { meaning: '洛水、洛阳，寓意温婉动人，才华出众', category: '水', tone: 4, pinyin: 'luò' },
  '玥': { meaning: '神珠、明珠，寓意珍贵美好，光彩夺目', category: '玉石', tone: 4, pinyin: 'yuè' },
  '瑾': { meaning: '美玉、美德，寓意品德高尚，如玉般温润', category: '玉石', tone: 3, pinyin: 'jǐn' },
  '瑜': { meaning: '美玉、优点，寓意完美无瑕，才华出众', category: '玉石', tone: 2, pinyin: 'yú' },
  '琛': { meaning: '珍宝、宝物，寓意珍贵稀有，价值连城', category: '玉石', tone: 1, pinyin: 'chēn' },
  '瑶': { meaning: '美玉、美好，寓意珍贵美好，光彩照人', category: '玉石', tone: 2, pinyin: 'yáo' },
  '琪': { meaning: '美玉、珍异，寓意珍贵美好，才华出众', category: '玉石', tone: 2, pinyin: 'qí' },
  '琬': { meaning: '美玉、美好，寓意温婉美好，品德高尚', category: '玉石', tone: 3, pinyin: 'wǎn' },
  '琰': { meaning: '美玉、光泽，寓意光彩照人，品德高尚', category: '玉石', tone: 3, pinyin: 'yǎn' },
  '璇': { meaning: '美玉、北斗星，寓意珍贵美好，光彩夺目', category: '玉石', tone: 2, pinyin: 'xuán' },
  '苒': { meaning: '草木茂盛，寓意生机勃勃，岁月静好', category: '植物', tone: 3, pinyin: 'rǎn' },
  '桐': { meaning: '梧桐树，寓意高洁品格，凤凰来仪', category: '植物', tone: 2, pinyin: 'tóng' },
  '枫': { meaning: '枫树、红叶，寓意热情浪漫，成熟稳重', category: '植物', tone: 1, pinyin: 'fēng' },
  '松': { meaning: '松树，寓意坚韧不拔，品格高洁', category: '植物', tone: 1, pinyin: 'sōng' },
  '柏': { meaning: '柏树，寓意正直坚强，长青不老', category: '植物', tone: 3, pinyin: 'bǎi' },
  '竹': { meaning: '竹子，寓意虚心有节，君子之风', category: '植物', tone: 2, pinyin: 'zhú' },
  '梅': { meaning: '梅花，寓意傲雪凌霜，坚强不屈', category: '植物', tone: 2, pinyin: 'méi' },
  '兰': { meaning: '兰花，寓意幽雅高洁，清香自持', category: '植物', tone: 2, pinyin: 'lán' },
  '荷': { meaning: '荷花、荷叶，寓意出淤泥而不染', category: '植物', tone: 2, pinyin: 'hé' },
  '莲': { meaning: '莲花、莲子，寓意纯洁美好', category: '植物', tone: 2, pinyin: 'lián' },
  '芷': { meaning: '白芷、香草，寓意芬芳美好', category: '植物', tone: 3, pinyin: 'zhǐ' },
  '若': { meaning: '如同、好像，寓意温柔美好', category: '植物', tone: 4, pinyin: 'ruò' },
  '芙': { meaning: '芙蓉、荷花，寓意美丽动人', category: '植物', tone: 2, pinyin: 'fú' },
  '蓉': { meaning: '芙蓉、蓉城，寓意美丽动人', category: '植物', tone: 2, pinyin: 'róng' },
  '薇': { meaning: '蔷薇、紫薇，寓意美丽坚强', category: '植物', tone: 1, pinyin: 'wēi' },
  '萱': { meaning: '萱草、忘忧，寓意无忧无虑', category: '植物', tone: 1, pinyin: 'xuān' },
  '棠': { meaning: '海棠、棠梨，寓意美丽动人', category: '植物', tone: 2, pinyin: 'táng' },
  '景': { meaning: '景色、景象，寓意前程美好', category: '天象', tone: 3, pinyin: 'jǐng' },
  '星': { meaning: '星辰、星光，寓意闪耀独特', category: '天象', tone: 1, pinyin: 'xīng' },
  '云': { meaning: '云彩、飘逸，寓意自由自在', category: '天象', tone: 2, pinyin: 'yún' },
  '霞': { meaning: '彩霞、晚霞，寓意绚烂多彩', category: '天象', tone: 2, pinyin: 'xiá' },
  '怀': { meaning: '怀抱、怀念，寓意心胸宽广', category: '品德', tone: 2, pinyin: 'huái' },
  '嘉': { meaning: '美好、赞许，寓意优秀出众', category: '品德', tone: 1, pinyin: 'jiā' },
  '懿': { meaning: '美好、德行，寓意品德完美', category: '品德', tone: 4, pinyin: 'yì' },
  '宁': { meaning: '安宁、平静，寓意心境平和', category: '品德', tone: 2, pinyin: 'níng' },
  '安': { meaning: '平安、安定，寓意一生平安', category: '品德', tone: 1, pinyin: 'ān' },
  '行': { meaning: '行走、品行，寓意行动力强', category: '动作', tone: 2, pinyin: 'xíng' },
  '翔': { meaning: '飞翔、翱翔，寓意志向高远', category: '动作', tone: 2, pinyin: 'xiáng' },
  '思': { meaning: '思考、思念，寓意聪慧善思', category: '动作', tone: 1, pinyin: 'sī' },
  '语': { meaning: '言语、说话，寓意善于表达', category: '动作', tone: 3, pinyin: 'yǔ' },
  '鸿': { meaning: '大雁、宏大，寓意志向远大', category: '鸟类', tone: 2, pinyin: 'hóng' },
  '鹤': { meaning: '仙鹤、长寿，寓意高洁长寿', category: '鸟类', tone: 4, pinyin: 'hè' },
  '鹏': { meaning: '大鹏、前程，寓意鹏程万里', category: '鸟类', tone: 2, pinyin: 'péng' },
  '宇': { meaning: '宇宙、空间，寓意胸怀广阔', category: '空间', tone: 3, pinyin: 'yǔ' },
  '轩': { meaning: '轩窗、高大，寓意气度不凡', category: '空间', tone: 1, pinyin: 'xuān' },
  '婉': { meaning: '温婉、柔顺，寓意温柔贤淑', category: '品质', tone: 3, pinyin: 'wǎn' },
  '柔': { meaning: '柔和、温柔，寓意温柔体贴', category: '品质', tone: 2, pinyin: 'róu' },
  '雅': { meaning: '优雅、高雅，寓意举止优雅', category: '品质', tone: 3, pinyin: 'yǎ' },
  '静': { meaning: '安静、宁静，寓意心境平和', category: '品质', tone: 4, pinyin: 'jìng' },
  '初': { meaning: '开始、最初，寓意不忘初心', category: '自然', tone: 1, pinyin: 'chū' },
  '夏': { meaning: '夏天、华夏，寓意热情奔放', category: '自然', tone: 4, pinyin: 'xià' },
  '秋': { meaning: '秋天、收获，寓意成熟稳重', category: '自然', tone: 1, pinyin: 'qiū' },
  '悠': { meaning: '悠然、长远，寓意悠然自得', category: '自然', tone: 1, pinyin: 'yōu' },
  '雨': { meaning: '雨水、恩泽，寓意滋润万物', category: '雨', tone: 3, pinyin: 'yǔ' },
  '晴': { meaning: '晴天、晴朗，寓意阳光开朗', category: '雨', tone: 2, pinyin: 'qíng' },
  '霖': { meaning: '甘霖、连雨，寓意恩泽深厚', category: '雨', tone: 2, pinyin: 'lín' },
  '霏': { meaning: '雨雪纷飞，寓意温柔细腻', category: '雨', tone: 1, pinyin: 'fēi' },
  '峻': { meaning: '高峻、严厉，寓意高大挺拔', category: '山岳', tone: 4, pinyin: 'jùn' },
  '峰': { meaning: '山峰、顶峰，寓意勇攀高峰', category: '山岳', tone: 1, pinyin: 'fēng' },
  '岳': { meaning: '山岳、岳父，寓意稳重可靠', category: '山岳', tone: 4, pinyin: 'yuè' },
  '明': { meaning: '明亮、智慧，寓意聪明睿智', category: '光明', tone: 2, pinyin: 'míng' },
  '辉': { meaning: '光辉、辉煌，寓意光彩照人', category: '光明', tone: 1, pinyin: 'huī' },
  '耀': { meaning: '照耀、显耀，寓意光芒四射', category: '光明', tone: 4, pinyin: 'yào' },
  '书': { meaning: '书籍、书写，寓意学识渊博', category: '文化', tone: 1, pinyin: 'shū' },
  '墨': { meaning: '墨水、书画，寓意文采出众', category: '文化', tone: 4, pinyin: 'mò' },
  '诗': { meaning: '诗歌、诗意，寓意文采斐然', category: '文化', tone: 1, pinyin: 'shī' },
  '瑞': { meaning: '祥瑞、吉祥，寓意吉祥如意', category: '吉祥', tone: 4, pinyin: 'ruì' },
  '祥': { meaning: '吉祥、祥瑞，寓意吉祥如意', category: '吉祥', tone: 2, pinyin: 'xiáng' },
  '博': { meaning: '博学、广博，寓意学识渊博', category: '才华', tone: 2, pinyin: 'bó' },
  '睿': { meaning: '睿智、明智，寓意聪明睿智', category: '才华', tone: 4, pinyin: 'ruì' },
  // 新增500个汉字
  '华': { meaning: '华丽、中华，寓意光彩夺目，才华横溢', category: '光明', tone: 2, pinyin: 'huá' },
  '文': { meaning: '文采、文化，寓意学识渊博，文采斐然', category: '文化', tone: 2, pinyin: 'wén' },
  '武': { meaning: '武艺、勇猛，寓意英勇无畏，刚健有力', category: '品德', tone: 3, pinyin: 'wǔ' },
  '德': { meaning: '道德、品德，寓意品德高尚，德才兼备', category: '品德', tone: 2, pinyin: 'dé' },
  '仁': { meaning: '仁爱、仁慈，寓意心地善良，仁者爱人', category: '品德', tone: 2, pinyin: 'rén' },
  '义': { meaning: '正义、道义，寓意正直不阿，重情重义', category: '品德', tone: 4, pinyin: 'yì' },
  '礼': { meaning: '礼仪、礼貌，寓意知书达理，彬彬有礼', category: '品德', tone: 3, pinyin: 'lǐ' },
  '智': { meaning: '智慧、聪明，寓意聪明睿智，才智过人', category: '才华', tone: 4, pinyin: 'zhì' },
  '信': { meaning: '诚信、信任，寓意诚实守信，言而有信', category: '品德', tone: 4, pinyin: 'xìn' },
  '忠': { meaning: '忠诚、忠心，寓意忠心耿耿，尽职尽责', category: '品德', tone: 1, pinyin: 'zhōng' },
  '孝': { meaning: '孝顺、孝敬，寓意孝顺父母，尊敬长辈', category: '品德', tone: 4, pinyin: 'xiào' },
  '和': { meaning: '和谐、和睦，寓意和睦相处，和气生财', category: '品德', tone: 2, pinyin: 'hé' },
  '平': { meaning: '平安、平和，寓意平平安安，心平气和', category: '品德', tone: 2, pinyin: 'píng' },
  '顺': { meaning: '顺利、顺心，寓意事事顺遂，一帆风顺', category: '吉祥', tone: 4, pinyin: 'shùn' },
  '康': { meaning: '健康、安康，寓意身体健康，平安喜乐', category: '吉祥', tone: 1, pinyin: 'kāng' },
  '泰': { meaning: '安泰、康泰，寓意国泰民安，万事亨通', category: '吉祥', tone: 4, pinyin: 'tài' },
  '乐': { meaning: '快乐、欢乐，寓意乐观开朗，幸福美满', category: '品德', tone: 4, pinyin: 'lè' },
  '福': { meaning: '幸福、福气，寓意福气满满，幸福安康', category: '吉祥', tone: 2, pinyin: 'fú' },
  '禄': { meaning: '福禄、俸禄，寓意福禄双全，富贵荣华', category: '吉祥', tone: 4, pinyin: 'lù' },
  '寿': { meaning: '长寿、寿命，寓意健康长寿，福寿绵长', category: '吉祥', tone: 4, pinyin: 'shòu' },
  '喜': { meaning: '欢喜、喜庆，寓意喜气洋洋，欢天喜地', category: '吉祥', tone: 3, pinyin: 'xǐ' },
  '财': { meaning: '财富、财产，寓意财源广进，富贵有余', category: '吉祥', tone: 2, pinyin: 'cái' },
  '富': { meaning: '富贵、富有，寓意富贵荣华，生活富足', category: '吉祥', tone: 4, pinyin: 'fù' },
  '贵': { meaning: '高贵、尊贵，寓意身份尊贵，品格高贵', category: '品德', tone: 4, pinyin: 'guì' },
  '荣': { meaning: '荣耀、繁荣，寓意荣华富贵，光宗耀祖', category: '吉祥', tone: 2, pinyin: 'róng' },
  '耀': { meaning: '照耀、显耀，寓意光芒四射，才华出众', category: '光明', tone: 4, pinyin: 'yào' },
  '光': { meaning: '光明、光彩，寓意光明磊落，前程光明', category: '光明', tone: 1, pinyin: 'guāng' },
  '亮': { meaning: '明亮、响亮，寓意聪明伶俐，前途光明', category: '光明', tone: 4, pinyin: 'liàng' },
  '晶': { meaning: '晶莹、水晶，寓意晶莹剔透，纯洁无瑕', category: '玉石', tone: 1, pinyin: 'jīng' },
  '莹': { meaning: '晶莹、莹润，寓意晶莹剔透，温润如玉', category: '玉石', tone: 2, pinyin: 'yíng' },
  '琳': { meaning: '美玉、琳琅，寓意珍贵美好，琳琅满目', category: '玉石', tone: 2, pinyin: 'lín' },
  '琅': { meaning: '琳琅、琅琅，寓意美好珍贵，书声琅琅', category: '玉石', tone: 2, pinyin: 'láng' },
  '琦': { meaning: '美玉、珍奇，寓意珍贵美好，与众不同', category: '玉石', tone: 2, pinyin: 'qí' },
  '玮': { meaning: '美玉、珍贵，寓意珍贵美好，才华出众', category: '玉石', tone: 3, pinyin: 'wěi' },
  '珺': { meaning: '美玉、美好，寓意珍贵美好，品德高尚', category: '玉石', tone: 4, pinyin: 'jùn' },
  '珏': { meaning: '双玉、玉佩，寓意成双成对，美好圆满', category: '玉石', tone: 2, pinyin: 'jué' },
  '瑞': { meaning: '祥瑞、吉祥，寓意吉祥如意，瑞气盈门', category: '吉祥', tone: 4, pinyin: 'ruì' },
  '珍': { meaning: '珍贵、珍珠，寓意珍贵美好，价值连城', category: '玉石', tone: 1, pinyin: 'zhēn' },
  '珠': { meaning: '珍珠、宝珠，寓意珍贵美好，光彩夺目', category: '玉石', tone: 1, pinyin: 'zhū' },
  '宝': { meaning: '宝贝、宝贵，寓意珍贵难得，价值连城', category: '玉石', tone: 3, pinyin: 'bǎo' },
  '玉': { meaning: '美玉、玉石，寓意温润如玉，品德高洁', category: '玉石', tone: 4, pinyin: 'yù' },
  '金': { meaning: '黄金、珍贵，寓意富贵荣华，价值连城', category: '玉石', tone: 1, pinyin: 'jīn' },
  '银': { meaning: '白银、纯洁，寓意纯洁美好，富贵吉祥', category: '玉石', tone: 2, pinyin: 'yín' },
  '锦': { meaning: '锦绣、华美，寓意前程似锦，生活美好', category: '文化', tone: 3, pinyin: 'jǐn' },
  '绣': { meaning: '刺绣、锦绣，寓意心灵手巧，美好精致', category: '文化', tone: 4, pinyin: 'xiù' },
  '绮': { meaning: '绮丽、华美，寓意华丽美好，文采斐然', category: '文化', tone: 3, pinyin: 'qǐ' },
  '绣': { meaning: '刺绣、锦绣，寓意心灵手巧，美好精致', category: '文化', tone: 4, pinyin: 'xiù' },
  '纨': { meaning: '纨绔、细绢，寓意富贵荣华，生活优渥', category: '文化', tone: 2, pinyin: 'wán' },
  '素': { meaning: '朴素、纯洁，寓意朴素无华，纯洁善良', category: '品质', tone: 4, pinyin: 'sù' },
  '洁': { meaning: '洁净、纯洁，寓意纯洁无瑕，品行端正', category: '品质', tone: 2, pinyin: 'jié' },
  '纯': { meaning: '纯洁、纯粹，寓意纯洁善良，纯粹真诚', category: '品质', tone: 2, pinyin: 'chún' },
  '真': { meaning: '真实、真诚，寓意真诚待人，真实可靠', category: '品德', tone: 1, pinyin: 'zhēn' },
  '善': { meaning: '善良、善心，寓意心地善良，与人为善', category: '品德', tone: 4, pinyin: 'shàn' },
  '美': { meaning: '美丽、美好，寓意容貌美丽，心灵美好', category: '品质', tone: 3, pinyin: 'měi' },
  '好': { meaning: '美好、良好，寓意生活美好，一切顺利', category: '吉祥', tone: 3, pinyin: 'hǎo' },
  '佳': { meaning: '佳人、美好，寓意美好出众，才貌双全', category: '品质', tone: 1, pinyin: 'jiā' },
  '妙': { meaning: '美妙、奇妙，寓意美妙绝伦，与众不同', category: '品质', tone: 4, pinyin: 'miào' },
  '丽': { meaning: '美丽、秀丽，寓意容貌美丽，气质优雅', category: '品质', tone: 4, pinyin: 'lì' },
  '艳': { meaning: '艳丽、鲜艳，寓意光彩照人，美丽动人', category: '品质', tone: 4, pinyin: 'yàn' },
  '娇': { meaning: '娇美、娇柔，寓意娇美动人，温柔可爱', category: '品质', tone: 1, pinyin: 'jiāo' },
  '娜': { meaning: '婀娜、袅娜，寓意姿态优美，婀娜多姿', category: '品质', tone: 4, pinyin: 'nà' },
  '婷': { meaning: '婷婷、娉婷，寓意亭亭玉立，姿态优美', category: '品质', tone: 2, pinyin: 'tíng' },
  '媛': { meaning: '名媛、美女，寓意美丽贤淑，才华出众', category: '品质', tone: 4, pinyin: 'yuàn' },
  '娟': { meaning: '娟秀、婵娟，寓意容貌秀丽，姿态优美', category: '品质', tone: 1, pinyin: 'juān' },
  '姝': { meaning: '美女、美好，寓意美丽动人，才德兼备', category: '品质', tone: 1, pinyin: 'shū' },
  '姣': { meaning: '姣好、美丽，寓意容貌姣好，美丽动人', category: '品质', tone: 1, pinyin: 'jiāo' },
  '娆': { meaning: '妖娆、娇娆，寓意妩媚动人，风姿绰约', category: '品质', tone: 2, pinyin: 'ráo' },
  '媚': { meaning: '妩媚、媚态，寓意妩媚动人，魅力十足', category: '品质', tone: 4, pinyin: 'mèi' },
  '倩': { meaning: '倩影、美丽，寓意美丽动人，姿态优雅', category: '品质', tone: 4, pinyin: 'qiàn' },
  '姿': { meaning: '姿态、姿色，寓意姿态优美，容貌出众', category: '品质', tone: 1, pinyin: 'zī' },
  '容': { meaning: '容貌、包容，寓意容貌美丽，心胸宽广', category: '品质', tone: 2, pinyin: 'róng' },
  '颜': { meaning: '容颜、颜色，寓意容貌美丽，光彩照人', category: '品质', tone: 2, pinyin: 'yán' },
  '玉': { meaning: '美玉、玉石，寓意温润如玉，品德高洁', category: '玉石', tone: 4, pinyin: 'yù' },
  '冰': { meaning: '冰雪、纯洁，寓意冰清玉洁，纯洁无瑕', category: '水', tone: 1, pinyin: 'bīng' },
  '雪': { meaning: '雪花、纯洁，寓意纯洁无瑕，高洁美丽', category: '水', tone: 3, pinyin: 'xuě' },
  '霜': { meaning: '霜雪、高洁，寓意高洁坚贞，不畏严寒', category: '水', tone: 1, pinyin: 'shuāng' },
  '露': { meaning: '露水、甘露，寓意清新纯洁，恩泽滋润', category: '水', tone: 4, pinyin: 'lù' },
  '雾': { meaning: '雾气、朦胧，寓意朦胧美丽，神秘迷人', category: '水', tone: 4, pinyin: 'wù' },
  '虹': { meaning: '彩虹、美丽，寓意美丽绚烂，前程似锦', category: '天象', tone: 2, pinyin: 'hóng' },
  '霓': { meaning: '霓虹、美丽，寓意光彩夺目，美丽动人', category: '天象', tone: 2, pinyin: 'ní' },
  '彩': { meaning: '彩色、光彩，寓意丰富多彩，光彩照人', category: '天象', tone: 3, pinyin: 'cǎi' },
  '霞': { meaning: '彩霞、晚霞，寓意绚烂多彩，美好灿烂', category: '天象', tone: 2, pinyin: 'xiá' },
  '云': { meaning: '云彩、飘逸，寓意自由自在，飘逸洒脱', category: '天象', tone: 2, pinyin: 'yún' },
  '月': { meaning: '月亮、明月，寓意纯洁美好，温柔皎洁', category: '天象', tone: 4, pinyin: 'yuè' },
  '星': { meaning: '星辰、星光，寓意闪耀独特，璀璨夺目', category: '天象', tone: 1, pinyin: 'xīng' },
  '日': { meaning: '太阳、光明，寓意光明磊落，朝气蓬勃', category: '天象', tone: 4, pinyin: 'rì' },
  '阳': { meaning: '阳光、太阳，寓意阳光开朗，积极向上', category: '天象', tone: 2, pinyin: 'yáng' },
  '天': { meaning: '天空、天地，寓意志向高远，胸怀广阔', category: '天象', tone: 1, pinyin: 'tiān' },
  '空': { meaning: '天空、空灵，寓意空灵通透，心胸开阔', category: '天象', tone: 1, pinyin: 'kōng' },
  '风': { meaning: '风光、风采，寓意风采照人，风度翩翩', category: '自然', tone: 1, pinyin: 'fēng' },
  '花': { meaning: '花朵、美丽，寓意美丽动人，如花似玉', category: '植物', tone: 1, pinyin: 'huā' },
  '草': { meaning: '草木、生机，寓意生机勃勃，坚韧不拔', category: '植物', tone: 3, pinyin: 'cǎo' },
  '木': { meaning: '树木、木材，寓意坚韧不拔，生机勃勃', category: '植物', tone: 4, pinyin: 'mù' },
  '林': { meaning: '树林、森林，寓意生机勃勃，繁荣昌盛', category: '植物', tone: 2, pinyin: 'lín' },
  '森': { meaning: '森林、茂盛，寓意生机勃勃，繁荣茂盛', category: '植物', tone: 1, pinyin: 'sēn' },
  '枝': { meaning: '树枝、枝丫，寓意生机勃勃，开枝散叶', category: '植物', tone: 1, pinyin: 'zhī' },
  '叶': { meaning: '树叶、叶子，寓意生机勃勃，枝繁叶茂', category: '植物', tone: 4, pinyin: 'yè' },
  '根': { meaning: '根本、根基，寓意根基稳固，不忘根本', category: '植物', tone: 1, pinyin: 'gēn' },
  '果': { meaning: '果实、结果，寓意硕果累累，收获满满', category: '植物', tone: 3, pinyin: 'guǒ' },
  '实': { meaning: '实在、果实，寓意脚踏实地，硕果累累', category: '品德', tone: 2, pinyin: 'shí' },
  '丰': { meaning: '丰收、丰富，寓意丰收富足，丰富多彩', category: '吉祥', tone: 1, pinyin: 'fēng' },
  '硕': { meaning: '硕果累累、硕大，寓意硕果累累，成就丰硕', category: '植物', tone: 4, pinyin: 'shuò' },
  '茂': { meaning: '茂盛、茂密，寓意生机勃勃，繁荣茂盛', category: '植物', tone: 4, pinyin: 'mào' },
  '盛': { meaning: '盛开、兴盛，寓意繁荣兴盛，蒸蒸日上', category: '吉祥', tone: 4, pinyin: 'shèng' },
  '昌': { meaning: '昌盛、兴旺，寓意繁荣昌盛，兴旺发达', category: '吉祥', tone: 1, pinyin: 'chāng' },
  '兴': { meaning: '兴旺、兴盛，寓意兴旺发达，欣欣向荣', category: '吉祥', tone: 1, pinyin: 'xīng' },
  '旺': { meaning: '兴旺、旺盛，寓意兴旺发达，生机勃勃', category: '吉祥', tone: 4, pinyin: 'wàng' },
  '发': { meaning: '发财、发展，寓意财源广进，发展顺利', category: '吉祥', tone: 1, pinyin: 'fā' },
  '达': { meaning: '发达、到达，寓意飞黄腾达，心想事成', category: '吉祥', tone: 2, pinyin: 'dá' },
  '通': { meaning: '通达、通顺，寓意通达事理，一帆风顺', category: '吉祥', tone: 1, pinyin: 'tōng' },
  '达': { meaning: '发达、到达，寓意飞黄腾达，心想事成', category: '吉祥', tone: 2, pinyin: 'dá' },
  '进': { meaning: '进步、进取，寓意积极进取，不断进步', category: '动作', tone: 4, pinyin: 'jìn' },
  '升': { meaning: '上升、提升，寓意步步高升，不断进步', category: '动作', tone: 1, pinyin: 'shēng' },
  '高': { meaning: '高大、高尚，寓意品德高尚，志向高远', category: '品德', tone: 1, pinyin: 'gāo' },
  '远': { meaning: '远大、远方，寓意志向远大，前程远大', category: '空间', tone: 3, pinyin: 'yuǎn' },
  '深': { meaning: '深厚、深远，寓意学识深厚，影响深远', category: '水', tone: 1, pinyin: 'shēn' },
  '厚': { meaning: '厚道、深厚，寓意为人厚道，情谊深厚', category: '品德', tone: 4, pinyin: 'hòu' },
  '重': { meaning: '重要、稳重，寓意稳重可靠，重要非凡', category: '品德', tone: 4, pinyin: 'zhòng' },
  '稳': { meaning: '稳重、稳定，寓意稳重可靠，稳步前行', category: '品德', tone: 3, pinyin: 'wěn' },
  '定': { meaning: '安定、确定，寓意安定稳重，处事果断', category: '品德', tone: 4, pinyin: 'dìng' },
  '坚': { meaning: '坚强、坚定，寓意坚强不屈，意志坚定', category: '品德', tone: 1, pinyin: 'jiān' },
  '强': { meaning: '强大、坚强，寓意强大有力，自强不息', category: '品德', tone: 2, pinyin: 'qiáng' },
  '刚': { meaning: '刚强、刚毅，寓意刚强不屈，坚毅果敢', category: '品德', tone: 1, pinyin: 'gāng' },
  '毅': { meaning: '坚毅、毅力，寓意坚毅果敢，有毅力', category: '品德', tone: 4, pinyin: 'yì' },
  '勇': { meaning: '勇敢、勇猛，寓意勇敢无畏，勇往直前', category: '品德', tone: 3, pinyin: 'yǒng' },
  '猛': { meaning: '勇猛、猛烈，寓意勇猛果敢，气势如虹', category: '品德', tone: 3, pinyin: 'měng' },
  '威': { meaning: '威严、威风，寓意威风凛凛，气势非凡', category: '品德', tone: 1, pinyin: 'wēi' },
  '武': { meaning: '武艺、勇猛，寓意英勇无畏，刚健有力', category: '品德', tone: 3, pinyin: 'wǔ' },
  '雄': { meaning: '雄壮、英雄，寓意志向远大，英雄气概', category: '品德', tone: 2, pinyin: 'xióng' },
  '豪': { meaning: '豪迈、豪杰，寓意豪迈奔放，英雄豪杰', category: '品德', tone: 2, pinyin: 'háo' },
  '杰': { meaning: '杰出、俊杰，寓意杰出非凡，才华横溢', category: '才华', tone: 2, pinyin: 'jié' },
  '俊': { meaning: '俊秀、英俊，寓意容貌俊秀，才华出众', category: '品质', tone: 4, pinyin: 'jùn' },
  '英': { meaning: '英俊、英才，寓意英姿飒爽，才华出众', category: '品质', tone: 1, pinyin: 'yīng' },
  '才': { meaning: '才能、才华，寓意才华横溢，才华出众', category: '才华', tone: 2, pinyin: 'cái' },
  '能': { meaning: '能力、才能，寓意能力出众，才华横溢', category: '才华', tone: 2, pinyin: 'néng' },
  '贤': { meaning: '贤德、贤能，寓意品德高尚，才能出众', category: '品德', tone: 2, pinyin: 'xián' },
  '良': { meaning: '善良、良好，寓意心地善良，品德良好', category: '品德', tone: 2, pinyin: 'liáng' },
  '正': { meaning: '正直、正义，寓意正直不阿，公正无私', category: '品德', tone: 4, pinyin: 'zhèng' },
  '直': { meaning: '正直、直率，寓意正直不阿，直率坦诚', category: '品德', tone: 2, pinyin: 'zhí' },
  '方': { meaning: '方正、方圆，寓意为人方正，处事有方', category: '品德', tone: 1, pinyin: 'fāng' },
  '圆': { meaning: '圆满、圆润，寓意圆满完美，处事圆融', category: '吉祥', tone: 2, pinyin: 'yuán' },
  '满': { meaning: '圆满、满足，寓意圆满完美，知足常乐', category: '吉祥', tone: 3, pinyin: 'mǎn' },
  '盈': { meaning: '丰盈、盈余，寓意收获满满，盈余富足', category: '吉祥', tone: 2, pinyin: 'yíng' },
  '余': { meaning: '盈余、富余，寓意富余充足，年年有余', category: '吉祥', tone: 2, pinyin: 'yú' },
  '庆': { meaning: '庆祝、喜庆，寓意喜庆欢乐，庆祝成功', category: '吉祥', tone: 4, pinyin: 'qìng' },
  '贺': { meaning: '祝贺、庆贺，寓意祝贺成功，喜庆欢乐', category: '吉祥', tone: 4, pinyin: 'hè' },
  '祝': { meaning: '祝福、祝愿，寓意祝福美好，心想事成', category: '吉祥', tone: 4, pinyin: 'zhù' },
  '愿': { meaning: '愿望、心愿，寓意心想事成，愿望达成', category: '吉祥', tone: 4, pinyin: 'yuàn' },
  '梦': { meaning: '梦想、梦幻，寓意梦想成真，美好如梦', category: '自然', tone: 4, pinyin: 'mèng' },
  '想': { meaning: '理想、思想，寓意志存高远，思想深刻', category: '动作', tone: 3, pinyin: 'xiǎng' },
  '志': { meaning: '志向、志气，寓意志存高远，志向远大', category: '品德', tone: 4, pinyin: 'zhì' },
  '愿': { meaning: '愿望、心愿，寓意心想事成，愿望达成', category: '吉祥', tone: 4, pinyin: 'yuàn' },
  '望': { meaning: '希望、期望，寓意充满希望，期望美好', category: '动作', tone: 4, pinyin: 'wàng' },
  '盼': { meaning: '盼望、期盼，寓意满怀期盼，期待美好', category: '动作', tone: 4, pinyin: 'pàn' },
  '期': { meaning: '期望、期待，寓意充满期待，期待美好', category: '动作', tone: 1, pinyin: 'qī' },
  '待': { meaning: '等待、期待', category: '动作', tone: 4, pinyin: 'dài' },
  '春': { meaning: '春天、春季，寓意生机勃勃，春意盎然', category: '自然', tone: 1, pinyin: 'chūn' },
  '夏': { meaning: '夏天、夏季，寓意热情奔放，生机勃勃', category: '自然', tone: 4, pinyin: 'xià' },
  '秋': { meaning: '秋天、秋季，寓意收获满满，硕果累累', category: '自然', tone: 1, pinyin: 'qiū' },
  '冬': { meaning: '冬天、冬季，寓意坚韧不拔，厚积薄发', category: '自然', tone: 1, pinyin: 'dōng' },
  '朝': { meaning: '朝阳、朝气，寓意朝气蓬勃，充满希望', category: '时间', tone: 1, pinyin: 'zhāo' },
  '暮': { meaning: '暮色、日落，寓意温婉动人，岁月静好', category: '时间', tone: 4, pinyin: 'mù' },
  '夕': { meaning: '夕阳、傍晚，寓意温婉动人，岁月静好', category: '时间', tone: 1, pinyin: 'xī' },
  '晓': { meaning: '清晨、明白，寓意聪慧明理，如晨光般清新', category: '时间', tone: 3, pinyin: 'xiǎo' },
  '旦': { meaning: '元旦、早晨，寓意新的开始，充满希望', category: '时间', tone: 4, pinyin: 'dàn' },
  '昔': { meaning: '昔日、往昔，寓意珍惜时光，不忘初心', category: '时间', tone: 1, pinyin: 'xī' },
  '今': { meaning: '今天、如今，寓意珍惜当下，把握现在', category: '时间', tone: 1, pinyin: 'jīn' },
  '古': { meaning: '古代、古典，寓意古典优雅，传承文化', category: '时间', tone: 3, pinyin: 'gǔ' },
  '新': { meaning: '新颖、新鲜，寓意新颖独特，焕然一新', category: '品质', tone: 1, pinyin: 'xīn' },
  '旧': { meaning: '怀旧、陈旧，寓意怀旧感恩，珍惜过去', category: '时间', tone: 4, pinyin: 'jiù' },
  '老': { meaning: '老师、老成，寓意老成持重，经验丰富', category: '品德', tone: 3, pinyin: 'lǎo' },
  '少': { meaning: '少年、年轻', category: '时间', tone: 4, pinyin: 'shào' },
  '青': { meaning: '青春、青色，寓意青春永驻，朝气蓬勃', category: '颜色', tone: 1, pinyin: 'qīng' },
  '蓝': { meaning: '蓝色、蓝天，寓意志向高远，心境开阔', category: '颜色', tone: 2, pinyin: 'lán' },
  '绿': { meaning: '绿色、生机，寓意生机勃勃，青春活力', category: '颜色', tone: 4, pinyin: 'lǜ' },
  '红': { meaning: '红色、喜庆，寓意红红火火，喜气洋洋', category: '颜色', tone: 2, pinyin: 'hóng' },
  '紫': { meaning: '紫色、紫气，寓意紫气东来，高贵典雅', category: '颜色', tone: 3, pinyin: 'zǐ' },
  '黄': { meaning: '黄色、金黄', category: '颜色', tone: 2, pinyin: 'huáng' },
  '白': { meaning: '白色、纯洁，寓意纯洁无瑕，清白正直', category: '颜色', tone: 2, pinyin: 'bái' },
  '黑': { meaning: '黑色、深沉，寓意沉稳内敛，深不可测', category: '颜色', tone: 1, pinyin: 'hēi' },
  '灰': { meaning: '灰色、沉稳，寓意沉稳内敛，处事稳重', category: '颜色', tone: 1, pinyin: 'huī' },
  '彤': { meaning: '红色、彤云', category: '颜色', tone: 2, pinyin: 'tóng' },
  '丹': { meaning: '红色、丹心', category: '颜色', tone: 1, pinyin: 'dān' },
  '翠': { meaning: '翠绿、翡翠', category: '颜色', tone: 4, pinyin: 'cuì' },
  '碧': { meaning: '碧绿、碧玉', category: '颜色', tone: 4, pinyin: 'bì' },
  '苍': { meaning: '苍白、苍穹', category: '颜色', tone: 1, pinyin: 'cāng' },
  '玄': { meaning: '玄妙、玄黑', category: '颜色', tone: 2, pinyin: 'xuán' },
  '素': { meaning: '素净、朴素', category: '颜色', tone: 4, pinyin: 'sù' },
  '青': { meaning: '青色、青春', category: '颜色', tone: 1, pinyin: 'qīng' },
  '朱': { meaning: '朱红、朱砂', category: '颜色', tone: 1, pinyin: 'zhū' },
  '绛': { meaning: '深红、绛紫', category: '颜色', tone: 4, pinyin: 'jiàng' },
  '绯': { meaning: '绯红、红色', category: '颜色', tone: 1, pinyin: 'fēi' },
  '黛': { meaning: '青黑、黛眉', category: '颜色', tone: 4, pinyin: 'dài' },
  '墨': { meaning: '墨水、黑色', category: '颜色', tone: 4, pinyin: 'mò' },
  '翰': { meaning: '翰林、文采', category: '文化', tone: 4, pinyin: 'hàn' },
  '章': { meaning: '文章、章法', category: '文化', tone: 1, pinyin: 'zhāng' },
  '篇': { meaning: '篇章、诗篇', category: '文化', tone: 1, pinyin: 'piān' },
  '韵': { meaning: '韵味、韵律', category: '文化', tone: 4, pinyin: 'yùn' },
  '律': { meaning: '规律、音律', category: '文化', tone: 4, pinyin: 'lǜ' },
  '调': { meaning: '音调、格调', category: '文化', tone: 4, pinyin: 'diào' },
  '曲': { meaning: '歌曲、乐曲', category: '文化', tone: 3, pinyin: 'qǔ' },
  '歌': { meaning: '歌曲、歌唱', category: '文化', tone: 1, pinyin: 'gē' },
  '舞': { meaning: '舞蹈、舞动', category: '动作', tone: 3, pinyin: 'wǔ' },
  '乐': { meaning: '音乐、快乐', category: '文化', tone: 4, pinyin: 'yuè' },
  '琴': { meaning: '古琴、琴艺', category: '文化', tone: 2, pinyin: 'qín' },
  '棋': { meaning: '棋艺、围棋', category: '文化', tone: 2, pinyin: 'qí' },
  '画': { meaning: '书画、绘画', category: '文化', tone: 4, pinyin: 'huà' },
  '书': { meaning: '书写、书法', category: '文化', tone: 1, pinyin: 'shū' },
  '印': { meaning: '印章、印记', category: '文化', tone: 4, pinyin: 'yìn' },
  '玺': { meaning: '玉玺、印章', category: '文化', tone: 3, pinyin: 'xǐ' },
  '鼎': { meaning: '鼎立、鼎盛', category: '文化', tone: 3, pinyin: 'dǐng' },
  '彝': { meaning: '彝器、礼器', category: '文化', tone: 2, pinyin: 'yí' },
  '爵': { meaning: '爵位、酒杯', category: '文化', tone: 2, pinyin: 'jué' },
  '尊': { meaning: '尊敬、尊贵', category: '品德', tone: 1, pinyin: 'zūn' },
  '鼎': { meaning: '鼎盛、鼎立', category: '文化', tone: 3, pinyin: 'dǐng' },
  '彝': { meaning: '彝器、礼器', category: '文化', tone: 2, pinyin: 'yí' },
  '爵': { meaning: '爵位、尊贵', category: '文化', tone: 2, pinyin: 'jué' },
  '尊': { meaning: '尊贵、尊敬', category: '品德', tone: 1, pinyin: 'zūn' },
  '崇': { meaning: '崇高、崇拜', category: '品德', tone: 2, pinyin: 'chóng' },
  '尚': { meaning: '高尚、时尚', category: '品德', tone: 4, pinyin: 'shàng' },
  '雅': { meaning: '高雅、优雅', category: '品质', tone: 3, pinyin: 'yǎ' },
  '致': { meaning: '精致、导致', category: '品质', tone: 4, pinyin: 'zhì' },
  '精': { meaning: '精神、精华', category: '品质', tone: 1, pinyin: 'jīng' },
  '神': { meaning: '精神、神灵', category: '品质', tone: 2, pinyin: 'shén' },
  '灵': { meaning: '灵动、灵气', category: '品质', tone: 2, pinyin: 'líng' },
  '秀': { meaning: '秀丽、优秀', category: '品质', tone: 4, pinyin: 'xiù' },
  '慧': { meaning: '智慧、聪慧', category: '才华', tone: 4, pinyin: 'huì' },
  '敏': { meaning: '敏捷、灵敏', category: '才华', tone: 3, pinyin: 'mǐn' },
  '捷': { meaning: '敏捷、快捷', category: '才华', tone: 2, pinyin: 'jié' },
  '睿': { meaning: '睿智、明智', category: '才华', tone: 4, pinyin: 'ruì' },
  '颖': { meaning: '聪颖、新颖', category: '才华', tone: 3, pinyin: 'yǐng' },
  '卓': { meaning: '卓越、高超', category: '才华', tone: 2, pinyin: 'zhuó' },
  '超': { meaning: '超越、高超', category: '才华', tone: 1, pinyin: 'chāo' },
  '越': { meaning: '超越、跨越', category: '才华', tone: 4, pinyin: 'yuè' },
  '飞': { meaning: '飞翔、飞扬', category: '动作', tone: 1, pinyin: 'fēi' },
  '扬': { meaning: '飞扬、发扬', category: '动作', tone: 2, pinyin: 'yáng' },
  '腾': { meaning: '腾飞、升腾', category: '动作', tone: 2, pinyin: 'téng' },
  '跃': { meaning: '跳跃、飞跃', category: '动作', tone: 4, pinyin: 'yuè' },
  '奔': { meaning: '奔跑、奔驰', category: '动作', tone: 1, pinyin: 'bēn' },
  '驰': { meaning: '奔驰、飞驰', category: '动作', tone: 2, pinyin: 'chí' },
  '骋': { meaning: '驰骋、奔放', category: '动作', tone: 3, pinyin: 'chěng' },
  '凌': { meaning: '凌云、凌驾', category: '动作', tone: 2, pinyin: 'líng' },
  '翔': { meaning: '翱翔、飞翔', category: '动作', tone: 2, pinyin: 'xiáng' },
  '翱': { meaning: '翱翔、飞翔', category: '动作', tone: 2, pinyin: 'áo' },
  '翥': { meaning: '飞举、高飞', category: '动作', tone: 4, pinyin: 'zhù' },
  '骞': { meaning: '飞腾、高举', category: '动作', tone: 1, pinyin: 'qiān' },
  '举': { meaning: '举动、举办', category: '动作', tone: 3, pinyin: 'jǔ' },
  '振': { meaning: '振奋、振兴', category: '动作', tone: 4, pinyin: 'zhèn' },
  '兴': { meaning: '兴旺、兴盛', category: '吉祥', tone: 1, pinyin: 'xīng' },
  '奋': { meaning: '奋斗、奋发', category: '动作', tone: 4, pinyin: 'fèn' },
  '发': { meaning: '发展、发达', category: '吉祥', tone: 1, pinyin: 'fā' },
  '拓': { meaning: '开拓、拓展', category: '动作', tone: 4, pinyin: 'tuò' },
  '展': { meaning: '发展、展现', category: '动作', tone: 3, pinyin: 'zhǎn' },
  '宏': { meaning: '宏大、宏伟', category: '空间', tone: 2, pinyin: 'hóng' },
  '阔': { meaning: '宽阔、广阔', category: '空间', tone: 4, pinyin: 'kuò' },
  '广': { meaning: '广大、广阔', category: '空间', tone: 3, pinyin: 'guǎng' },
  '博': { meaning: '博学、广博', category: '才华', tone: 2, pinyin: 'bó' },
  '大': { meaning: '伟大、大小', category: '空间', tone: 4, pinyin: 'dà' },
  '巨': { meaning: '巨大、巨人', category: '空间', tone: 4, pinyin: 'jù' },
  '伟': { meaning: '伟大、雄伟', category: '品德', tone: 3, pinyin: 'wěi' },
  '雄': { meaning: '英雄、雄伟', category: '品德', tone: 2, pinyin: 'xióng' },
  '英': { meaning: '英雄、英勇', category: '品质', tone: 1, pinyin: 'yīng' },
  '豪': { meaning: '豪迈、豪杰', category: '品德', tone: 2, pinyin: 'háo' },
  '壮': { meaning: '壮大、雄壮', category: '品质', tone: 4, pinyin: 'zhuàng' },
  '丽': { meaning: '美丽、秀丽', category: '品质', tone: 4, pinyin: 'lì' },
  '伟': { meaning: '伟大、雄伟', category: '品德', tone: 3, pinyin: 'wěi' },
  '俊': { meaning: '俊秀、英俊', category: '品质', tone: 4, pinyin: 'jùn' },
  '俏': { meaning: '俊俏、俏丽', category: '品质', tone: 4, pinyin: 'qiào' },
  '倩': { meaning: '倩影、美丽', category: '品质', tone: 4, pinyin: 'qiàn' },
  '姣': { meaning: '姣好、美丽', category: '品质', tone: 1, pinyin: 'jiāo' },
  '娆': { meaning: '妖娆、娇娆', category: '品质', tone: 2, pinyin: 'ráo' },
  '媚': { meaning: '妩媚、媚态', category: '品质', tone: 4, pinyin: 'mèi' },
  '妩': { meaning: '妩媚、多姿', category: '品质', tone: 3, pinyin: 'wǔ' },
  '娜': { meaning: '婀娜、袅娜', category: '品质', tone: 4, pinyin: 'nà' },
  '婷': { meaning: '婷婷、娉婷', category: '品质', tone: 2, pinyin: 'tíng' },
  '媛': { meaning: '名媛、美女', category: '品质', tone: 4, pinyin: 'yuàn' },
  '娟': { meaning: '娟秀、婵娟', category: '品质', tone: 1, pinyin: 'juān' },
  '姝': { meaning: '美女、美好', category: '品质', tone: 1, pinyin: 'shū' },
  '娥': { meaning: '嫦娥、美女', category: '品质', tone: 2, pinyin: 'é' },
  '妃': { meaning: '贵妃、妃子', category: '品质', tone: 1, pinyin: 'fēi' },
  '姬': { meaning: '美女、歌姬', category: '品质', tone: 1, pinyin: 'jī' },
  '妾': { meaning: '侍妾、谦卑', category: '品质', tone: 4, pinyin: 'qiè' },
  '婢': { meaning: '侍女、谦卑', category: '品质', tone: 4, pinyin: 'bì' },
  '奴': { meaning: '奴隶、谦卑', category: '品质', tone: 2, pinyin: 'nú' },
  '仆': { meaning: '仆人、谦卑', category: '品质', tone: 2, pinyin: 'pú' },
  '役': { meaning: '劳役、服务', category: '动作', tone: 4, pinyin: 'yì' },
  '使': { meaning: '使者、使用', category: '动作', tone: 3, pinyin: 'shǐ' },
  '令': { meaning: '命令、美好', category: '动作', tone: 4, pinyin: 'lìng' },
  '命': { meaning: '生命、命运', category: '抽象', tone: 4, pinyin: 'mìng' },
  '运': { meaning: '运气、运动', category: '抽象', tone: 4, pinyin: 'yùn' },
  '气': { meaning: '气息、气质', category: '抽象', tone: 4, pinyin: 'qì' },
  '息': { meaning: '气息、休息', category: '抽象', tone: 1, pinyin: 'xī' },
  '脉': { meaning: '脉络、血脉', category: '抽象', tone: 4, pinyin: 'mài' },
  '络': { meaning: '网络、脉络', category: '抽象', tone: 4, pinyin: 'luò' },
  '系': { meaning: '系统、关系', category: '抽象', tone: 4, pinyin: 'xì' },
  '统': { meaning: '统一、系统', category: '抽象', tone: 3, pinyin: 'tǒng' },
  '总': { meaning: '总结、总领', category: '抽象', tone: 3, pinyin: 'zǒng' },
  '理': { meaning: '理想、道理', category: '抽象', tone: 3, pinyin: 'lǐ' },
  '道': { meaning: '道路、道理', category: '抽象', tone: 4, pinyin: 'dào' },
  '德': { meaning: '道德、品德', category: '品德', tone: 2, pinyin: 'dé' },
  '义': { meaning: '正义、道义', category: '品德', tone: 4, pinyin: 'yì' },
  '礼': { meaning: '礼仪、礼貌', category: '品德', tone: 3, pinyin: 'lǐ' },
  '仁': { meaning: '仁爱、仁慈', category: '品德', tone: 2, pinyin: 'rén' },
  '智': { meaning: '智慧、聪明', category: '才华', tone: 4, pinyin: 'zhì' },
  '信': { meaning: '诚信、信任', category: '品德', tone: 4, pinyin: 'xìn' },
  '忠': { meaning: '忠诚、忠心', category: '品德', tone: 1, pinyin: 'zhōng' },
  '孝': { meaning: '孝顺、孝敬', category: '品德', tone: 4, pinyin: 'xiào' },
  '悌': { meaning: '孝悌、敬爱', category: '品德', tone: 4, pinyin: 'tì' },
  '廉': { meaning: '廉洁、廉正', category: '品德', tone: 2, pinyin: 'lián' },
  '耻': { meaning: '羞耻、耻辱', category: '品德', tone: 3, pinyin: 'chǐ' },
  '勇': { meaning: '勇敢、勇猛', category: '品德', tone: 3, pinyin: 'yǒng' },
  '毅': { meaning: '坚毅、毅力', category: '品德', tone: 4, pinyin: 'yì' },
  '刚': { meaning: '刚强、刚毅', category: '品德', tone: 1, pinyin: 'gāng' },
  '强': { meaning: '强大、坚强', category: '品德', tone: 2, pinyin: 'qiáng' },
  '健': { meaning: '健康、强健', category: '吉祥', tone: 4, pinyin: 'jiàn' },
  '康': { meaning: '健康、安康', category: '吉祥', tone: 1, pinyin: 'kāng' },
  '泰': { meaning: '安泰、康泰', category: '吉祥', tone: 4, pinyin: 'tài' },
  '宁': { meaning: '安宁、平静', category: '品德', tone: 2, pinyin: 'níng' },
  '安': { meaning: '平安、安定', category: '品德', tone: 1, pinyin: 'ān' },
  '顺': { meaning: '顺利、顺心', category: '吉祥', tone: 4, pinyin: 'shùn' },
  '遂': { meaning: '顺遂、成功', category: '吉祥', tone: 4, pinyin: 'suì' },
  '利': { meaning: '利益、顺利', category: '吉祥', tone: 4, pinyin: 'lì' },
  '吉': { meaning: '吉祥、吉利', category: '吉祥', tone: 2, pinyin: 'jí' },
  '祥': { meaning: '吉祥、祥瑞', category: '吉祥', tone: 2, pinyin: 'xiáng' },
  '瑞': { meaning: '祥瑞、吉祥', category: '吉祥', tone: 4, pinyin: 'ruì' },
  '福': { meaning: '幸福、福气', category: '吉祥', tone: 2, pinyin: 'fú' },
  '禄': { meaning: '福禄、俸禄', category: '吉祥', tone: 4, pinyin: 'lù' },
  '寿': { meaning: '长寿、寿命', category: '吉祥', tone: 4, pinyin: 'shòu' },
  '喜': { meaning: '欢喜、喜庆', category: '吉祥', tone: 3, pinyin: 'xǐ' },
  '乐': { meaning: '快乐、欢乐', category: '品德', tone: 4, pinyin: 'lè' },
  '欢': { meaning: '欢乐、欢喜', category: '品德', tone: 1, pinyin: 'huān' },
  '庆': { meaning: '庆祝、喜庆', category: '吉祥', tone: 4, pinyin: 'qìng' },
  '贺': { meaning: '祝贺、庆贺', category: '吉祥', tone: 4, pinyin: 'hè' },
  '祝': { meaning: '祝福、祝愿', category: '吉祥', tone: 4, pinyin: 'zhù' },
  '愿': { meaning: '愿望、心愿', category: '吉祥', tone: 4, pinyin: 'yuàn' },
  '祈': { meaning: '祈求、祈祷', category: '动作', tone: 2, pinyin: 'qí' },
  '祷': { meaning: '祈祷、祷告', category: '动作', tone: 3, pinyin: 'dǎo' },
  '求': { meaning: '请求、追求', category: '动作', tone: 2, pinyin: 'qiú' },
  '索': { meaning: '求索、索取', category: '动作', tone: 3, pinyin: 'suǒ' },
  '探': { meaning: '探索、探讨', category: '动作', tone: 4, pinyin: 'tàn' },
  '究': { meaning: '研究、究竟', category: '动作', tone: 1, pinyin: 'jiū' },
  '研': { meaning: '研究、研习', category: '动作', tone: 2, pinyin: 'yán' },
  '习': { meaning: '学习、习惯', category: '动作', tone: 2, pinyin: 'xí' },
  '学': { meaning: '学习、学问', category: '才华', tone: 2, pinyin: 'xué' },
  '问': { meaning: '问题、学问', category: '才华', tone: 4, pinyin: 'wèn' },
  '知': { meaning: '知道、知识', category: '才华', tone: 1, pinyin: 'zhī' },
  '识': { meaning: '认识、知识', category: '才华', tone: 2, pinyin: 'shí' },
  '见': { meaning: '看见、见解', category: '动作', tone: 4, pinyin: 'jiàn' },
  '闻': { meaning: '听闻、名声', category: '动作', tone: 2, pinyin: 'wén' },
  '听': { meaning: '听力、听从', category: '动作', tone: 1, pinyin: 'tīng' },
  '观': { meaning: '观看、观点', category: '动作', tone: 1, pinyin: 'guān' },
  '察': { meaning: '观察、察觉', category: '动作', tone: 2, pinyin: 'chá' },
  '觉': { meaning: '感觉、觉悟', category: '动作', tone: 2, pinyin: 'jué' },
  '悟': { meaning: '领悟、觉悟', category: '动作', tone: 4, pinyin: 'wù' },
  '感': { meaning: '感觉、感情', category: '抽象', tone: 3, pinyin: 'gǎn' },
  '情': { meaning: '感情、情况', category: '抽象', tone: 2, pinyin: 'qíng' },
  '爱': { meaning: '爱心、爱情', category: '品德', tone: 4, pinyin: 'ài' },
  '怜': { meaning: '可怜、怜爱', category: '品德', tone: 2, pinyin: 'lián' },
  '惜': { meaning: '珍惜、可惜', category: '品德', tone: 1, pinyin: 'xī' },
  '惠': { meaning: '恩惠、贤惠', category: '品德', tone: 4, pinyin: 'huì' },
  '慈': { meaning: '慈爱、慈祥', category: '品德', tone: 2, pinyin: 'cí' },
  '善': { meaning: '善良、善心', category: '品德', tone: 4, pinyin: 'shàn' },
  '良': { meaning: '善良、良好', category: '品德', tone: 2, pinyin: 'liáng' },
  '贤': { meaning: '贤德、贤能', category: '品德', tone: 2, pinyin: 'xián' },
  '圣': { meaning: '神圣、圣人', category: '品德', tone: 4, pinyin: 'shèng' },
  '贤': { meaning: '贤德、贤良', category: '品德', tone: 2, pinyin: 'xián' },
  '明': { meaning: '明亮、聪明', category: '光明', tone: 2, pinyin: 'míng' },
  '亮': { meaning: '明亮、响亮', category: '光明', tone: 4, pinyin: 'liàng' },
  '光': { meaning: '光明、光彩', category: '光明', tone: 1, pinyin: 'guāng' },
  '辉': { meaning: '光辉、辉煌', category: '光明', tone: 1, pinyin: 'huī' },
  '耀': { meaning: '照耀、显耀', category: '光明', tone: 4, pinyin: 'yào' },
  '晖': { meaning: '阳光、光辉', category: '时间', tone: 1, pinyin: 'huī' },
  '曦': { meaning: '晨光、阳光', category: '时间', tone: 1, pinyin: 'xī' },
  '晨': { meaning: '清晨、早晨', category: '时间', tone: 2, pinyin: 'chén' },
  '昕': { meaning: '黎明、日出', category: '时间', tone: 1, pinyin: 'xīn' },
  '晓': { meaning: '清晨、明白', category: '时间', tone: 3, pinyin: 'xiǎo' },
  '旭': { meaning: '旭日东升', category: '时间', tone: 4, pinyin: 'xù' },
  '旦': { meaning: '元旦、早晨', category: '时间', tone: 4, pinyin: 'dàn' },
  '朝': { meaning: '朝阳、朝气', category: '时间', tone: 1, pinyin: 'zhāo' },
  '夕': { meaning: '夕阳、傍晚', category: '时间', tone: 1, pinyin: 'xī' },
  '暮': { meaning: '暮色、日落', category: '时间', tone: 4, pinyin: 'mù' },
  '晚': { meaning: '晚上、晚年', category: '时间', tone: 3, pinyin: 'wǎn' },
  '夜': { meaning: '夜晚、夜色', category: '时间', tone: 4, pinyin: 'yè' },
  '时': { meaning: '时间、时光', category: '时间', tone: 2, pinyin: 'shí' },
  '光': { meaning: '光明、时光', category: '光明', tone: 1, pinyin: 'guāng' },
  '辰': { meaning: '星辰、时光', category: '时间', tone: 2, pinyin: 'chén' },
  '星': { meaning: '星辰、星光', category: '天象', tone: 1, pinyin: 'xīng' },
  '宿': { meaning: '星宿、住宿', category: '天象', tone: 4, pinyin: 'sù' },
  '斗': { meaning: '北斗、斗争', category: '天象', tone: 3, pinyin: 'dǒu' },
  '牛': { meaning: '牵牛、牛宿', category: '天象', tone: 2, pinyin: 'niú' },
  '女': { meaning: '织女、女子', category: '品质', tone: 3, pinyin: 'nǚ' },
  '虚': { meaning: '虚宿、虚心', category: '天象', tone: 1, pinyin: 'xū' },
  '危': { meaning: '危宿、危险', category: '天象', tone: 1, pinyin: 'wēi' },
  '室': { meaning: '室宿、房屋', category: '天象', tone: 4, pinyin: 'shì' },
  '壁': { meaning: '壁宿、墙壁', category: '天象', tone: 4, pinyin: 'bì' },
  '奎': { meaning: '奎宿、奎星', category: '天象', tone: 2, pinyin: 'kuí' },
  '娄': { meaning: '娄宿、姓氏', category: '天象', tone: 2, pinyin: 'lóu' },
  '胃': { meaning: '胃宿、胃口', category: '天象', tone: 4, pinyin: 'wèi' },
  '昴': { meaning: '昴宿、星宿', category: '天象', tone: 3, pinyin: 'mǎo' },
  '毕': { meaning: '毕宿、毕业', category: '天象', tone: 4, pinyin: 'bì' },
  '觜': { meaning: '觜宿、星宿', category: '天象', tone: 1, pinyin: 'zī' },
  '参': { meaning: '参宿、参与', category: '天象', tone: 1, pinyin: 'shēn' },
  '井': { meaning: '井宿、水井', category: '天象', tone: 3, pinyin: 'jǐng' },
  '鬼': { meaning: '鬼宿、神秘', category: '天象', tone: 3, pinyin: 'guǐ' },
  '柳': { meaning: '柳宿、柳树', category: '天象', tone: 3, pinyin: 'liǔ' },
  '星': { meaning: '星宿、星辰', category: '天象', tone: 1, pinyin: 'xīng' },
  '张': { meaning: '张宿、张开', category: '天象', tone: 1, pinyin: 'zhāng' },
  '翼': { meaning: '翼宿、翅膀', category: '天象', tone: 4, pinyin: 'yì' },
  '轸': { meaning: '轸宿、星宿', category: '天象', tone: 3, pinyin: 'zhěn' },
  '角': { meaning: '角宿、角落', category: '天象', tone: 3, pinyin: 'jiǎo' },
  '亢': { meaning: '亢宿、高昂', category: '天象', tone: 4, pinyin: 'kàng' },
  '氐': { meaning: '氐宿、根底', category: '天象', tone: 1, pinyin: 'dī' },
  '房': { meaning: '房宿、房屋', category: '天象', tone: 2, pinyin: 'fáng' },
  '心': { meaning: '心宿、心脏', category: '天象', tone: 1, pinyin: 'xīn' },
  '尾': { meaning: '尾宿、尾巴', category: '天象', tone: 3, pinyin: 'wěi' },
  '箕': { meaning: '箕宿、簸箕', category: '天象', tone: 1, pinyin: 'jī' },
  '青': { meaning: '青龙、青色', category: '天象', tone: 1, pinyin: 'qīng' },
  '龙': { meaning: '青龙、龙', category: '动物', tone: 2, pinyin: 'lóng' },
  '白': { meaning: '白虎、白色', category: '颜色', tone: 2, pinyin: 'bái' },
  '虎': { meaning: '白虎、老虎', category: '动物', tone: 3, pinyin: 'hǔ' },
  '朱': { meaning: '朱雀、红色', category: '颜色', tone: 1, pinyin: 'zhū' },
  '雀': { meaning: '朱雀、麻雀', category: '鸟类', tone: 4, pinyin: 'què' },
  '玄': { meaning: '玄武、玄黑', category: '颜色', tone: 2, pinyin: 'xuán' },
  '武': { meaning: '玄武、武术', category: '品德', tone: 3, pinyin: 'wǔ' },
  '东': { meaning: '东方、东边', category: '方位', tone: 1, pinyin: 'dōng' },
  '西': { meaning: '西方、西边', category: '方位', tone: 1, pinyin: 'xī' },
  '南': { meaning: '南方、南边', category: '方位', tone: 2, pinyin: 'nán' },
  '北': { meaning: '北方、北边', category: '方位', tone: 3, pinyin: 'běi' },
  '中': { meaning: '中央、中国', category: '方位', tone: 1, pinyin: 'zhōng' },
  '央': { meaning: '中央、央求', category: '方位', tone: 1, pinyin: 'yāng' },
  '上': { meaning: '上方、上面', category: '方位', tone: 4, pinyin: 'shàng' },
  '下': { meaning: '下方、下面', category: '方位', tone: 4, pinyin: 'xià' },
  '左': { meaning: '左边、左方', category: '方位', tone: 3, pinyin: 'zuǒ' },
  '右': { meaning: '右边、右方', category: '方位', tone: 4, pinyin: 'yòu' },
  '前': { meaning: '前面、前方', category: '方位', tone: 2, pinyin: 'qián' },
  '后': { meaning: '后面、后方', category: '方位', tone: 4, pinyin: 'hòu' },
  '内': { meaning: '内部、里面', category: '方位', tone: 4, pinyin: 'nèi' },
  '外': { meaning: '外部、外面', category: '方位', tone: 4, pinyin: 'wài' },
  '里': { meaning: '里面、内部', category: '方位', tone: 3, pinyin: 'lǐ' },
  '间': { meaning: '中间、房间', category: '方位', tone: 1, pinyin: 'jiān' },
  '旁': { meaning: '旁边、侧面', category: '方位', tone: 2, pinyin: 'páng' },
  '侧': { meaning: '侧面、侧身', category: '方位', tone: 4, pinyin: 'cè' },
  '边': { meaning: '旁边、边缘', category: '方位', tone: 1, pinyin: 'biān' },
  '缘': { meaning: '边缘、缘分', category: '方位', tone: 2, pinyin: 'yuán' },
  '周': { meaning: '周围、周全', category: '方位', tone: 1, pinyin: 'zhōu' },
  '围': { meaning: '周围、包围', category: '方位', tone: 2, pinyin: 'wéi' },
  '域': { meaning: '领域、区域', category: '空间', tone: 4, pinyin: 'yù' },
  '区': { meaning: '区域、地区', category: '空间', tone: 1, pinyin: 'qū' },
  '境': { meaning: '境界、环境', category: '空间', tone: 4, pinyin: 'jìng' },
  '界': { meaning: '界限、世界', category: '空间', tone: 4, pinyin: 'jiè' },
  '宇': { meaning: '宇宙、空间', category: '空间', tone: 3, pinyin: 'yǔ' },
  '宙': { meaning: '宇宙、时间', category: '空间', tone: 4, pinyin: 'zhòu' },
  '穹': { meaning: '苍穹、天空', category: '空间', tone: 2, pinyin: 'qióng' },
  '苍': { meaning: '苍天、苍老', category: '颜色', tone: 1, pinyin: 'cāng' },
  '旻': { meaning: '天空、秋天', category: '空间', tone: 2, pinyin: 'mín' },
  '霄': { meaning: '云霄、天空', category: '空间', tone: 1, pinyin: 'xiāo' },
  '汉': { meaning: '银河、汉族', category: '空间', tone: 4, pinyin: 'hàn' },
  '河': { meaning: '河流、银河', category: '水', tone: 2, pinyin: 'hé' },
  '湖': { meaning: '湖泊、湖水', category: '水', tone: 2, pinyin: 'hú' },
  '海': { meaning: '大海、海洋', category: '水', tone: 3, pinyin: 'hǎi' },
  '洋': { meaning: '海洋、大洋', category: '水', tone: 2, pinyin: 'yáng' },
  '江': { meaning: '江河、长江', category: '水', tone: 1, pinyin: 'jiāng' },
  '池': { meaning: '池塘、池水', category: '水', tone: 2, pinyin: 'chí' },
  '潭': { meaning: '深潭、潭水', category: '水', tone: 2, pinyin: 'tán' },
  '渊': { meaning: '深渊、渊博', category: '水', tone: 1, pinyin: 'yuān' },
  '港': { meaning: '港口、港湾', category: '水', tone: 3, pinyin: 'gǎng' },
  '湾': { meaning: '海湾、港湾', category: '水', tone: 1, pinyin: 'wān' },
  '澳': { meaning: '港湾、澳门', category: '水', tone: 4, pinyin: 'ào' },
  '浦': { meaning: '水边、浦口', category: '水', tone: 3, pinyin: 'pǔ' },
  '渚': { meaning: '水中小洲', category: '水', tone: 3, pinyin: 'zhǔ' },
  '汀': { meaning: '水边平地', category: '水', tone: 1, pinyin: 'tīng' },
  '滨': { meaning: '水边、海滨', category: '水', tone: 1, pinyin: 'bīn' },
  '洲': { meaning: '水中陆地', category: '水', tone: 1, pinyin: 'zhōu' },
  '岛': { meaning: '岛屿、海岛', category: '山岳', tone: 3, pinyin: 'dǎo' },
  '屿': { meaning: '小岛、岛屿', category: '山岳', tone: 3, pinyin: 'yǔ' },
  '礁': { meaning: '礁石、暗礁', category: '山岳', tone: 1, pinyin: 'jiāo' },
  '岩': { meaning: '岩石、山岩', category: '山岳', tone: 2, pinyin: 'yán' },
  '石': { meaning: '石头、岩石', category: '山岳', tone: 2, pinyin: 'shí' },
  '矿': { meaning: '矿产、矿物', category: '山岳', tone: 4, pinyin: 'kuàng' },
  '砂': { meaning: '砂石、砂子', category: '山岳', tone: 1, pinyin: 'shā' },
  '砾': { meaning: '碎石、砂砾', category: '山岳', tone: 4, pinyin: 'lì' },
  '壤': { meaning: '土壤、泥土', category: '植物', tone: 3, pinyin: 'rǎng' },
  '土': { meaning: '土地、土壤', category: '植物', tone: 3, pinyin: 'tǔ' },
  '地': { meaning: '大地、地球', category: '空间', tone: 4, pinyin: 'dì' },
  '田': { meaning: '田地、农田', category: '植物', tone: 2, pinyin: 'tián' },
  '野': { meaning: '田野、野外', category: '植物', tone: 3, pinyin: 'yě' },
  '原': { meaning: '平原、原野', category: '植物', tone: 2, pinyin: 'yuán' },
  '坡': { meaning: '山坡、斜坡', category: '山岳', tone: 1, pinyin: 'pō' },
  '岗': { meaning: '山岗、岗位', category: '山岳', tone: 3, pinyin: 'gǎng' },
  '岭': { meaning: '山岭、山脉', category: '山岳', tone: 3, pinyin: 'lǐng' },
  '峦': { meaning: '山峦、峰峦', category: '山岳', tone: 2, pinyin: 'luán' },
  '嶂': { meaning: '山峰、层峦叠嶂', category: '山岳', tone: 4, pinyin: 'zhàng' },
  '崖': { meaning: '山崖、悬崖', category: '山岳', tone: 2, pinyin: 'yá' },
  '峡': { meaning: '峡谷、三峡', category: '山岳', tone: 2, pinyin: 'xiá' },
  '谷': { meaning: '山谷、峡谷', category: '山岳', tone: 3, pinyin: 'gǔ' },
  '壑': { meaning: '山沟、沟壑', category: '山岳', tone: 4, pinyin: 'hè' },
  '丘': { meaning: '山丘、丘陵', category: '山岳', tone: 1, pinyin: 'qiū' },
  '陵': { meaning: '山陵、陵墓', category: '山岳', tone: 2, pinyin: 'líng' },
  '坟': { meaning: '坟墓、坟地', category: '山岳', tone: 2, pinyin: 'fén' },
  '墓': { meaning: '坟墓、墓地', category: '山岳', tone: 4, pinyin: 'mù' },
  '碑': { meaning: '石碑、墓碑', category: '文化', tone: 1, pinyin: 'bēi' },
  '碣': { meaning: '石碑、石碣', category: '文化', tone: 2, pinyin: 'jié' },
  '础': { meaning: '基础、柱础', category: '建筑', tone: 3, pinyin: 'chǔ' },
  '柱': { meaning: '柱子、支柱', category: '建筑', tone: 4, pinyin: 'zhù' },
  '梁': { meaning: '房梁、桥梁', category: '建筑', tone: 2, pinyin: 'liáng' },
  '栋': { meaning: '栋梁、房屋', category: '建筑', tone: 4, pinyin: 'dòng' },
  '檐': { meaning: '屋檐、房檐', category: '建筑', tone: 2, pinyin: 'yán' },
  '廊': { meaning: '走廊、长廊', category: '建筑', tone: 2, pinyin: 'láng' },
  '榭': { meaning: '亭榭、水榭', category: '建筑', tone: 4, pinyin: 'xiè' },
  '阁': { meaning: '楼阁、阁楼', category: '建筑', tone: 2, pinyin: 'gé' },
  '楼': { meaning: '楼房、高楼', category: '建筑', tone: 2, pinyin: 'lóu' },
  '台': { meaning: '平台、台阶', category: '建筑', tone: 2, pinyin: 'tái' },
  '亭': { meaning: '亭子、凉亭', category: '建筑', tone: 2, pinyin: 'tíng' },
  '轩': { meaning: '轩窗、气宇轩昂', category: '建筑', tone: 1, pinyin: 'xuān' },
  '斋': { meaning: '书斋、斋戒', category: '建筑', tone: 1, pinyin: 'zhāi' },
  '舍': { meaning: '房舍、宿舍', category: '建筑', tone: 4, pinyin: 'shè' },
  '居': { meaning: '居住、居所', category: '建筑', tone: 1, pinyin: 'jū' },
  '宅': { meaning: '住宅、宅院', category: '建筑', tone: 2, pinyin: 'zhái' },
  '邸': { meaning: '府邸、宅邸', category: '建筑', tone: 3, pinyin: 'dǐ' },
  '府': { meaning: '府邸、官府', category: '建筑', tone: 3, pinyin: 'fǔ' },
  '庭': { meaning: '庭院、家庭', category: '建筑', tone: 2, pinyin: 'tíng' },
  '院': { meaning: '院子、庭院', category: '建筑', tone: 4, pinyin: 'yuàn' },
  '园': { meaning: '花园、园林', category: '建筑', tone: 2, pinyin: 'yuán' },
  '苑': { meaning: '园林、苑囿', category: '建筑', tone: 4, pinyin: 'yuàn' },
  '囿': { meaning: '苑囿、园林', category: '建筑', tone: 4, pinyin: 'yòu' },
  '圃': { meaning: '花圃、菜园', category: '建筑', tone: 3, pinyin: 'pǔ' },
  '囿': { meaning: '苑囿、园林', category: '建筑', tone: 4, pinyin: 'yòu' },
  '仓': { meaning: '仓库、粮仓', category: '建筑', tone: 1, pinyin: 'cāng' },
  '库': { meaning: '仓库、库房', category: '建筑', tone: 4, pinyin: 'kù' },
  '厨': { meaning: '厨房、厨师', category: '建筑', tone: 2, pinyin: 'chú' },
  '厕': { meaning: '厕所、卫生间', category: '建筑', tone: 4, pinyin: 'cè' },
  '室': { meaning: '房间、室内', category: '建筑', tone: 4, pinyin: 'shì' },
  '房': { meaning: '房屋、房间', category: '建筑', tone: 2, pinyin: 'fáng' },
  '屋': { meaning: '房屋、屋子', category: '建筑', tone: 1, pinyin: 'wū' },
  '家': { meaning: '家庭、家人', category: '建筑', tone: 1, pinyin: 'jiā' },
  '户': { meaning: '门户、家庭', category: '建筑', tone: 4, pinyin: 'hù' },
  '门': { meaning: '门户、门口', category: '建筑', tone: 2, pinyin: 'mén' },
  '窗': { meaning: '窗户、窗口', category: '建筑', tone: 1, pinyin: 'chuāng' },
  '牖': { meaning: '窗户、采光', category: '建筑', tone: 3, pinyin: 'yǒu' },
  '扉': { meaning: '门扉、柴扉', category: '建筑', tone: 1, pinyin: 'fēi' },
  '槛': { meaning: '门槛、栏杆', category: '建筑', tone: 4, pinyin: 'kǎn' },
  '梯': { meaning: '梯子、阶梯', category: '建筑', tone: 1, pinyin: 'tī' },
  '阶': { meaning: '台阶、阶梯', category: '建筑', tone: 1, pinyin: 'jiē' },
  '陛': { meaning: '台阶、陛下', category: '建筑', tone: 4, pinyin: 'bì' },
  '墀': { meaning: '台阶、空地', category: '建筑', tone: 2, pinyin: 'chí' },
  '砖': { meaning: '砖头、砖瓦', category: '建筑', tone: 1, pinyin: 'zhuān' },
  '瓦': { meaning: '瓦片、瓦解', category: '建筑', tone: 3, pinyin: 'wǎ' },
  '陶': { meaning: '陶瓷、陶器', category: '文化', tone: 2, pinyin: 'táo' },
  '瓷': { meaning: '瓷器、陶瓷', category: '文化', tone: 2, pinyin: 'cí' },
  '漆': { meaning: '油漆、漆器', category: '文化', tone: 1, pinyin: 'qī' },
  '雕': { meaning: '雕刻、雕塑', category: '文化', tone: 1, pinyin: 'diāo' },
  '塑': { meaning: '塑造、雕塑', category: '文化', tone: 4, pinyin: 'sù' },
  '铸': { meaning: '铸造、铸铁', category: '文化', tone: 4, pinyin: 'zhù' },
  '锻': { meaning: '锻炼、锻造', category: '动作', tone: 4, pinyin: 'duàn' },
  '冶': { meaning: '冶炼、陶冶', category: '动作', tone: 3, pinyin: 'yě' },
  '炼': { meaning: '锻炼、炼制', category: '动作', tone: 4, pinyin: 'liàn' },
  '熔': { meaning: '熔化、熔炼', category: '动作', tone: 2, pinyin: 'róng' },
  '焊': { meaning: '焊接、焊补', category: '动作', tone: 4, pinyin: 'hàn' },
  '接': { meaning: '连接、接触', category: '动作', tone: 1, pinyin: 'jiē' },
  '缝': { meaning: '缝合、缝隙', category: '动作', tone: 2, pinyin: 'féng' },
  '补': { meaning: '修补、补充', category: '动作', tone: 3, pinyin: 'bǔ' },
  '修': { meaning: '修理、修养', category: '动作', tone: 1, pinyin: 'xiū' },
  '建': { meaning: '建设、建立', category: '动作', tone: 4, pinyin: 'jiàn' },
  '造': { meaning: '制造、创造', category: '动作', tone: 4, pinyin: 'zào' },
  '筑': { meaning: '建筑、构筑', category: '动作', tone: 4, pinyin: 'zhù' },
  '构': { meaning: '构造、结构', category: '动作', tone: 4, pinyin: 'gòu' },
  '架': { meaning: '架子、架构', category: '建筑', tone: 4, pinyin: 'jià' },
  '搭': { meaning: '搭建、搭配', category: '动作', tone: 1, pinyin: 'dā' },
  '建': { meaning: '建设、建立', category: '动作', tone: 4, pinyin: 'jiàn' },
  '立': { meaning: '站立、建立', category: '动作', tone: 4, pinyin: 'lì' },
  '树': { meaning: '树木、树立', category: '植物', tone: 4, pinyin: 'shù' },
  '植': { meaning: '植物、种植', category: '植物', tone: 2, pinyin: 'zhí' },
  '栽': { meaning: '栽种、栽培', category: '动作', tone: 1, pinyin: 'zāi' },
  '培': { meaning: '培养、培育', category: '动作', tone: 2, pinyin: 'péi' },
  '育': { meaning: '教育、培育', category: '动作', tone: 4, pinyin: 'yù' },
  '养': { meaning: '养育、培养', category: '动作', tone: 3, pinyin: 'yǎng' },
  '生': { meaning: '生命、生长', category: '生命', tone: 1, pinyin: 'shēng' },
  '长': { meaning: '成长、长大', category: '动作', tone: 3, pinyin: 'zhǎng' },
  '成': { meaning: '成功、成就', category: '动作', tone: 2, pinyin: 'chéng' },
  '熟': { meaning: '成熟、熟悉', category: '动作', tone: 2, pinyin: 'shú' },
  '老': { meaning: '年老、老师', category: '时间', tone: 3, pinyin: 'lǎo' },
  '少': { meaning: '少年、年轻', category: '时间', tone: 4, pinyin: 'shào' },
  '幼': { meaning: '幼小、幼年', category: '时间', tone: 4, pinyin: 'yòu' },
  '稚': { meaning: '稚嫩、幼稚', category: '时间', tone: 4, pinyin: 'zhì' },
  '嫩': { meaning: '嫩绿、稚嫩', category: '时间', tone: 4, pinyin: 'nèn' },
  '初': { meaning: '开始、最初', category: '时间', tone: 1, pinyin: 'chū' },
  '始': { meaning: '开始、始终', category: '时间', tone: 3, pinyin: 'shǐ' },
  '终': { meaning: '终于、始终', category: '时间', tone: 1, pinyin: 'zhōng' },
  '末': { meaning: '末尾、末期', category: '时间', tone: 4, pinyin: 'mò' },
  '尾': { meaning: '尾巴、末尾', category: '动物', tone: 3, pinyin: 'wěi' },
  '尽': { meaning: '尽力、尽头', category: '动作', tone: 4, pinyin: 'jìn' },
  '完': { meaning: '完成、完美', category: '动作', tone: 2, pinyin: 'wán' },
  '毕': { meaning: '毕业、完成', category: '动作', tone: 4, pinyin: 'bì' },
  '竟': { meaning: '竟然、毕竟', category: '动作', tone: 4, pinyin: 'jìng' },
  '了': { meaning: '了解、了结', category: '动作', tone: 3, pinyin: 'le' },
  '结': { meaning: '结果、结束', category: '动作', tone: 2, pinyin: 'jié' },
  '束': { meaning: '结束、约束', category: '动作', tone: 4, pinyin: 'shù' },
  '局': { meaning: '局面、局势', category: '抽象', tone: 2, pinyin: 'jú' },
  '势': { meaning: '势力、形势', category: '抽象', tone: 4, pinyin: 'shì' },
  '态': { meaning: '态度、状态', category: '抽象', tone: 4, pinyin: 'tài' },
  '度': { meaning: '程度、态度', category: '抽象', tone: 4, pinyin: 'dù' },
  '量': { meaning: '数量、力量', category: '抽象', tone: 4, pinyin: 'liàng' },
  '数': { meaning: '数量、数学', category: '抽象', tone: 4, pinyin: 'shù' },
  '额': { meaning: '名额、额头', category: '抽象', tone: 2, pinyin: 'é' },
  '额': { meaning: '数量、额度', category: '抽象', tone: 2, pinyin: 'é' },
  '量': { meaning: '数量、力量', category: '抽象', tone: 4, pinyin: 'liàng' },
};

// 精选双字名（20个）
const curatedDoubleNames = [
  { name: "沐辰", pinyin: "mù chén", meaning: "如沐星辰之光，心怀广阔宇宙，寓意前程似锦，气度不凡。", source: "现代意境", style: "现代", tone: [4, 2] },
  { name: "望舒", pinyin: "wàng shū", meaning: "取自月神之名，如月光般高洁明亮，寓意温柔智慧，清辉普照。", source: "《楚辞·离骚》", style: "楚辞", tone: [4, 1] },
  { name: "呦呦", pinyin: "yōu yōu", meaning: "鹿鸣之声，悠扬动听，寓意生命力旺盛，性格开朗阳光。", source: "《诗经·小雅》", style: "诗经", tone: [1, 1] },
  { name: "思齐", pinyin: "sī qí", meaning: "见贤思齐焉，见不贤而内自省也，寓意见贤思齐，追求卓越。", source: "《诗经·大雅》", style: "诗经", tone: [1, 2] },
  { name: "怀瑾", pinyin: "huái jǐn", meaning: "怀揣美玉，怀抱美德，寓意品德高尚，内心纯洁如玉。", source: "《楚辞·九章》", style: "楚辞", tone: [2, 3] },
  { name: "景行", pinyin: "jǐng xíng", meaning: "高山仰止，景行行止，寓意德行高尚，令人敬仰。", source: "《诗经·小雅》", style: "诗经", tone: [3, 2] },
  { name: "清越", pinyin: "qīng yuè", meaning: "声音清脆悠扬，超越凡俗，寓意才华出众，气质高雅。", source: "自然意象", style: "自然", tone: [1, 4] },
  { name: "星阑", pinyin: "xīng lán", meaning: "夜色深沉，星光灿烂，寓意深邃迷人，光彩照人。", source: "唐诗意境", style: "唐诗", tone: [1, 2] },
  { name: "晓岚", pinyin: "xiǎo lán", meaning: "清晨山间雾气，缥缈如梦，寓意清新脱俗，灵动优雅。", source: "宋词意境", style: "宋词", tone: [3, 2] },
  { name: "逸然", pinyin: "yì rán", meaning: "安逸自然，超然物外，寓意生活从容，性情洒脱。", source: "现代意境", style: "现代", tone: [4, 2] },
  { name: "峻峰", pinyin: "jùn fēng", meaning: "高峻山峰，巍峨挺拔，寓意意志坚定，成就卓越。", source: "山水意境", style: "自然", tone: [4, 1] },
  { name: "语冰", pinyin: "yǔ bīng", meaning: "夏虫不可语冰，寓意见识广博，思想深刻，卓尔不群。", source: "《庄子》", style: "宋词", tone: [3, 1] },
  { name: "令仪", pinyin: "lìng yí", meaning: "仪态端庄优美，令人生敬，寓意举止大方，气质高贵。", source: "《诗经·大雅》", style: "诗经", tone: [4, 2] },
  { name: "海晏", pinyin: "hǎi yàn", meaning: "沧海平静，河清海晏，寓意天下太平，生活安稳顺遂。", source: "唐诗意境", style: "唐诗", tone: [3, 4] },
  { name: "予安", pinyin: "yǔ ān", meaning: "给予安宁，平安喜乐，寓意一生顺遂，内心宁静。", source: "现代意境", style: "现代", tone: [3, 1] },
  { name: "锦书", pinyin: "jǐn shū", meaning: "华美的书信，云中谁寄锦书来，寓意才华横溢，情意绵长。", source: "《一剪梅》", style: "宋词", tone: [3, 1] },
  { name: "云舒", pinyin: "yún shū", meaning: "去留无意，漫随天外云卷云舒，寓意心境豁达，从容自在。", source: "《幽窗小记》", style: "现代", tone: [2, 1] },
  { name: "知秋", pinyin: "zhī qiū", meaning: "一叶知秋，见微知著，寓意洞察敏锐，聪慧过人。", source: "《淮南子》", style: "现代", tone: [1, 1] },
  { name: "明哲", pinyin: "míng zhé", meaning: "明智睿哲，洞察世事，寓意聪明智慧，明辨是非。", source: "《诗经》", style: "诗经", tone: [2, 2] },
  { name: "若华", pinyin: "ruò huá", meaning: "若木之花，光彩照人，寓意容貌华美，生命璀璨。", source: "《楚辞·天问》", style: "楚辞", tone: [4, 2] },
];

// 生成双字名寓意描述
function generateDoubleMeaning(char1, char2, style) {
  const info1 = singleCharDB[char1];
  const info2 = singleCharDB[char2];
  
  if (!info1 || !info2) {
    return `${char1}${char2}相映成趣，寓意美好吉祥，${style}意境深远。`;
  }
  
  const templates = [
    `${info1.meaning.split('，')[0]}；${info2.meaning.split('，')[0]}。两字相配，${style}气韵浓厚。`,
    `取"${char1}"之${info1.meaning.split('，')[0]}，配"${char2}"之${info2.meaning.split('，')[0]}，寓意${style}意境深远。`,
    `${char1}${char2}合璧，${info1.meaning.split('，')[0]}，${info2.meaning.split('，')[0]}，${style}风雅自成。`,
    `"${char1}"者，${info1.meaning.split('，')[0]}；"${char2}"者，${info2.meaning.split('，')[0]}。合而为名，${style}意蕴悠长。`,
    `${char1}${char2}相生，${info1.meaning}；${info2.meaning}。整体寓意${style}之美。`,
  ];
  
  return templates[Math.floor(Math.random() * templates.length)];
}

// 生成2000个双字名
const doubleNames = [...curatedDoubleNames];
const availableChars = Object.keys(singleCharDB);
const styles = ['诗经', '楚辞', '唐诗', '宋词', '现代', '自然'];

while (doubleNames.length < 2000) {
  const char1 = availableChars[Math.floor(Math.random() * availableChars.length)];
  const char2 = availableChars[Math.floor(Math.random() * availableChars.length)];
  
  if (char1 === char2) continue;
  
  const name = char1 + char2;
  
  // 检查是否已存在
  if (doubleNames.some(item => item.name === name)) continue;
  
  const style = styles[Math.floor(Math.random() * styles.length)];
  const info1 = singleCharDB[char1];
  const info2 = singleCharDB[char2];
  const meaning = generateDoubleMeaning(char1, char2, style);
  
  doubleNames.push({
    name,
    pinyin: `${info1?.pinyin || char1} ${info2?.pinyin || char2}`,
    meaning,
    source: style === '诗经' ? '《诗经》意境' : 
            style === '楚辞' ? '《楚辞》意境' :
            style === '唐诗' ? '唐诗意境' :
            style === '宋词' ? '宋词意境' :
            style === '自然' ? '山水意境' : '现代意境',
    style: style,
    tone: [info1?.tone || 1, info2?.tone || 2]
  });
}

// 生成单字名（每个字只出现一次，不重复）
const singleNames = [];
const singleNameChars = Object.keys(singleCharDB);

for (const char of singleNameChars) {
  const info = singleCharDB[char];
  
  singleNames.push({
    name: char,
    pinyin: info.pinyin,
    meaning: info.meaning,
    source: '《中华字库》',
    style: '传统',
    tone: [info.tone, 0]
  });
}

// 合并所有名字
const allNames = [...doubleNames, ...singleNames];

// 写入JSON文件
const outputPath = path.join(__dirname, '..', 'public', 'names.json');
fs.writeFileSync(outputPath, JSON.stringify(allNames, null, 2));

console.log(`✅ 成功生成 ${allNames.length} 个名字`);
console.log(`📄 文件位置: ${outputPath}`);
console.log(`📊 单字名: ${singleNames.length} 个`);
console.log(`📊 双字名: ${doubleNames.length} 个`);
